travis:
  secure:
    BINSTAR_TOKEN: vL0TRSPiRrJXkL4n0vWuRCgijL0rpLpX8fI6ujp85Xmr9Mpb2vl5S6zw7DjhwRAbHnhtRjewh9TzTP83f9uT5N51GjogWeREllmQzGo9aoGN4bKF8d7T5cPCLWJQrXKR3kFJm0dFBVtPwy1PRsDSP4mzjn+dFKpQJ+voUtDR9Ztv1re2O3K6SfRlZeBBIeg6aFOhSf4ss9I7VPqSW/lsndxYBpGokct3GkUcvFJsk200gxb5tBZNuvuG5FH35WOfq8LPCGVnii2AKZBRAYHe6wZPdrxSBl1w59vGuv1yIL3yzkdHVxqrYgIjB6UlKrOP0A9CUEPuiYV7TNi9pfc5EhLasm5SFiOwEPafoNR1mtUfjIFC+ZD6rxw/3Jd9IybVV/IC7RJ/zzCMKVbxxKY1ReOom76O8nyOffiL/fErsFwzl0mcrwZGjHTwuyw0S33z5vLAqh59BV4/DRIyf8eD92sSTr+DrxhyHLYy2eJsQ6HHHlGwSPdFzzg6j8X1gTJGIO2vxiNH4VEzx+CgAVR9JsDfjHIfcXymL+tGCOJs3l/E/j2d7vg4TqryZpw8Fio7KKWwtZsLwo0pjgsrm5FQ6E560bbUS+5SRIRqBM4EdAVxfTAPNhPDkuTZj+WrSg79AWgljc3rQ0MjNSibrBP2Eoa4j9Ikpp2SNT26/rlahRE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
